var1= int(input ('enter the first number: '))
var2= int(input ('enter the second number: '   ))
print()
var3= (var1+var2)
var4= (var1-var2)
var5= (var1*var2)
var6= (var1/var2)
print("addition:" , var3)
print("subtraction:" , var4)
print("multiplication:" , var5)
print("division:" , var6)
